name: Java CI with Service Test

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew

    - name: Start Service in Background
      id: service_start # Даем шагу ID
      run: |
        java -jar ./artifacts/app-mbank.jar &
        SERVICE_PID=$!
        echo "Service started with PID $SERVICE_PID"
        # Сохраняем PID в переменную окружения для последующих шагов
        echo "SERVICE_PID=$SERVICE_PID" >> $GITHUB_ENV
        sleep 10
          
    - name: Run Tests
      run: ./gradlew test
      
    - name: Stop Service
      if: always()
      # $SERVICE_PID теперь доступен, потому что он был записан в $GITHUB_ENV
      run: |
        if [ -n "$SERVICE_PID" ]; then
          echo "Stopping service with PID $SERVICE_PID"
          kill $SERVICE_PID || true
        else
          echo "SERVICE_PID not found, skipping stop."
        fi
