name: Java CI with Service Test

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew

    - name: Start Service in Background
      run: |
        java -jar ./artifacts/app-mbank.jar &
        SERVICE_PID=$!
        echo "Service started with PID $SERVICE_PID"
        sleep 10
          
    - name: Run Tests
      run: ./gradlew test
      
    - name: Stop Service
      if: always()
      run: kill $SERVICE_PID || true
